name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test-jvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm: [8, 11, 17, 21, 25]
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v8
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - name: Run unit tests (JVM)
      run: scala-cli test . --jvm ${{ matrix.jvm }}

  test-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v8
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - run: npm install jsdom

    - name: Run unit tests (JS)
      run: scala-cli test . --js --dep org.scala-js::scalajs-dom::2.8.1

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v8
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true

    - name: Check formatting
      run: scala-cli fmt . --check

    - name: Compile README examples
      run: scala-cli compile --markdown README.md --scala 3.3.5 -cp "$(scala-cli compile . --print-classpath)"
